name: sembast_tutorial
description: A simple Sembast tutorial

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sembast: ^2.4.3
  get_it: ^4.0.2
  path_provider: ^1.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true